repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: check-merge-conflict
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        description: Format files with clang-format.
        entry: clang-format
        language: system
        files: \.(c|cpp|h|hpp)$
        args: ['--verbose', '-i', '--style=file']
